spring.jpa.hibernate.ddl-auto: create
#spring.datasource.url: "jdbc:mysql://localhost:3306/dbchat?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC"
spring.datasource.url: jdbc:mysql://localhost:3306/dbchat
spring.datasource.username: root
spring.datasource.password: 1234
spring.freemarker.expose-request-attributes: true